# Generated by Django 3.1.4 on 2024-08-26 13:53

import appdenoti.models
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('fone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Membro de equipe')),
                ('matricula', models.CharField(blank=True, max_length=15, unique=True, verbose_name='Matricula')),
                ('liberado', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', appdenoti.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(blank=True, max_length=100)),
                ('cnpj', models.IntegerField(blank=True, default=None, null=True, unique=True)),
                ('cpf', models.IntegerField(blank=True, default=None, null=True, unique=True)),
                ('endereco', models.CharField(max_length=100)),
                ('codigo_profissional', models.CharField(blank=True, default='', max_length=50)),
                ('cnae', models.IntegerField(blank=True, default=None, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('codigo_verificador', models.PositiveIntegerField(default=appdenoti.models.Notificacao.gerar_codigo_verificador, primary_key=True, serialize=False, unique=True)),
                ('notif', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, choices=[('CAD', 'Sem Cadastro'), ('ALV', 'Sem Alvará'), ('DEB', 'Em Debito'), ('SB', 'Sem Baixa')], default='', max_length=5)),
                ('observacao', models.CharField(blank=True, default='Sem Observação', max_length=500)),
                ('regularidade', models.BooleanField(default=False, null=True)),
                ('prazo', models.PositiveIntegerField(default=30, null=True)),
                ('entidade', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='appdenoti.entidade')),
                ('fiscal', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parecer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parecer', models.TextField(max_length=500)),
                ('data_parecer', models.DateTimeField(default=None, null=True)),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appdenoti.notificacao')),
            ],
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='uploads/')),
                ('nome_arquivo', models.CharField(max_length=50, unique=True)),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appdenoti.notificacao')),
            ],
        ),
    ]
