# Generated by Django 3.1.4 on 2024-08-29 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appdenoti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liberacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='appdenoti.entidade')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
