# Generated by Django 3.1.4 on 2024-08-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdenoti', '0002_liberacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liberacao',
            name='usuario',
        ),
        migrations.AddField(
            model_name='liberacao',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='liberacao',
            name='chave',
            field=models.IntegerField(verbose_name='Chave'),
        ),
    ]
