# Generated by Django 3.1.4 on 2024-08-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdenoti', '0003_auto_20240830_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liberacao',
            name='id',
        ),
        migrations.AlterField(
            model_name='liberacao',
            name='email',
            field=models.EmailField(default='', max_length=254, primary_key=True, serialize=False, verbose_name='E-mail'),
        ),
    ]
