# Generated by Django 3.1.4 on 2024-09-05 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appdenoti', '0004_auto_20240830_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='liberacao',
            name='data_criacao',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
