from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('cadastrarempresa', views.forment, name='cadastrarempresa'),
    path('criaentidade', views.criaentidade, name='criarentidade'),
    path('buscaempresa', views.buscaempresa, name='buscaempresa'),
    path('editarentidade/<int:pk>/', views.editarentidade, name='editarentidade'),
    path('alterarentidade/<int:pk>/', views.alterarentidade, name='alterarentidade'),
    path('deletarentidade/<int:pk>/', views.deletarentidade, name='deletarentidade'),
    path('regularizar/<int:pk>/', views.regularizar, name='regularizar'),
    path('visualizarentidade/<int:pk>/', views.visualizarentidade, name='visualizarentidade'),
    path('criarusuarioentidade', views.criaruser),
    path('formcadastro', views.usuariocad, name='cadastrarent'),
    path("accounts/", include("django.contrib.auth.urls"), name='loginoriginal'),
    path("login", views.loginredirect),
    path("notificar", views.CriarNotificacao, name='notificar'),
    path("salvarnotificacao", views.salvarnotificacao ),
    path('parecer', views.CriarParecer),
    path('salvarparecer', views.salvarparecer),
    path('buscanotificacao', views.buscanotificacao, name='buscanotificacao'),
    path('buscausuario', views.buscausuario, name='buscausuario'),
    path('visualizarnotificacao/<int:pk>/', views.visualizarnotificacao, name='visualizarnotificacao'),
    path('editarnotificacao/<int:pk>/', views.editarnotificacao, name='editarnotificacao'),
    path('alterarnotificacao/<int:pk>/', views.alterarnotificacao, name='alterarnotificacao'),
    path('generate_pdf/<int:codigo_verificador>/', views.generate_pdf, name='generate_pdf'),
    path('upload_arquivo/', views.criaarquivo, name='upload_arquivo'),
    path('download_arquivo/<int:arquivo_id>/', views.download_arquivo, name='download_arquivo'),
    path('validador/', views.validador),
    path('historico',views.historicousuario, name='historico'),
    path('paginausuario/<int:id>/', views.paginausuario, name='paginausuario'),
    path('filtros/', views.filtros, name='filtros'),
    path('filtrousuario/', views.filtrosue, name='filtrosusuario'),
    path('liberacao', views.liberacao, name='liberacao'),
    path('listaliberacao', views.listaliberacao, name='listaliberacao'),
    path('listaliberacao/<str:email>/', views.filtroliberacao, name='filtroliberacao'),

]