# Generated by Django 3.1.4 on 2024-05-22 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(default=None, max_length=100)),
                ('nome_fantasia', models.CharField(blank=True, max_length=100)),
                ('cnpj', models.IntegerField(blank=True, default=None, null=True)),
                ('cpf', models.IntegerField(blank=True, default=None, null=True)),
                ('endereco', models.CharField(max_length=100)),
                ('cp', models.CharField(blank=True, max_length=50, null=True)),
                ('cnae', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=256, null=True)),
                ('matricula', models.IntegerField(default=None)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('codigo_verificador', models.PositiveIntegerField(default=18959782, primary_key=True, serialize=False, unique=True)),
                ('notif', models.PositiveIntegerField(default=None)),
                ('data', models.DateTimeField(default=None)),
                ('motivo', models.CharField(choices=[('CAD', 'Sem Cadastro'), ('ALV', 'Sem Alvará'), ('DEB', 'Em Debito'), ('SB', 'Sem Baixa')], default=None, max_length=5)),
                ('observacao', models.CharField(max_length=500)),
                ('regularidade', models.BooleanField(default=False)),
                ('prazo', models.PositiveIntegerField(default=30)),
                ('entidade', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='noti.entidade')),
                ('fiscal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='noti.fiscal')),
            ],
        ),
        migrations.CreateModel(
            name='usuarioEntidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liberado', models.BooleanField(default=False)),
                ('escolha', models.CharField(choices=[('A', 'autonomo'), ('E', 'empresa')], default='A', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parecer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parecer', models.CharField(max_length=500)),
                ('data_parecer', models.DateTimeField(default=None)),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='noti.fiscal')),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='noti.notificacao')),
            ],
        ),
        migrations.AddField(
            model_name='entidade',
            name='usuario',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='noti.usuarioentidade'),
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='uploads/')),
                ('nome_arquivo', models.CharField(max_length=20)),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='noti.notificacao')),
            ],
        ),
    ]
