# Generated by Django 3.1.4 on 2024-05-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0005_auto_20240526_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='codigo_verificador',
            field=models.PositiveIntegerField(default=45748645, primary_key=True, serialize=False, unique=True),
        ),
    ]
