# Generated by Django 3.1.4 on 2024-06-02 00:01

from django.db import migrations, models
import noti.models


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0006_auto_20240526_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='codigo_verificador',
            field=models.PositiveIntegerField(default=noti.models.Notificacao.gerar_codigo_verificador, primary_key=True, serialize=False, unique=True),
        ),
    ]
