# Generated by Django 3.1.4 on 2024-06-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0007_auto_20240601_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioentidade',
            name='escolha',
            field=models.CharField(choices=[('Autonomo', 'autonomo'), ('Empresa', 'empresa')], default='A', max_length=10),
        ),
    ]
